export const houses=[
    {
        id: 1,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj_2IfynEp6ZlvL_8o8XReCsazf40z_StYrg&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://foyr.com/learn/wp-content/uploads/2021/09/master-bedroom-essentials.png",
        kitchenImageUrl: "https://images.livspace-cdn.com/plain/https://jumanji.livspace-cdn.com/magazine/wp-content/uploads/sites/2/2023/05/03113728/luxury-modern-kitchen-designs-regalia.jpg",
        livingAreaImageUrl: "https://images.livspace-cdn.com/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/ond-2022-1664872805-f0ijv/lr-1664874214-fOdlj/living-dining-1-1667989152-wJYA8.jpg",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 2,
        house: "3BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1673351762/Website/CMS-Uploads/_MG_0187_8_9_upjmgt.jpg",
        location: "Hyderabad",
        bedRoomImageUrl: "https://images.livspace-cdn.com/plain/https://jumanji.livspace-cdn.com/magazine/wp-content/uploads/sites/2/2022/06/10183457/small-bedroom-ideas.jpg",
        kitchenImageUrl: "https://images.woodenstreet.de/image/data/modular%20kitchen/22.jpg", 
        livingAreaImageUrl: "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&q=80&w=1000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bGl2aW5nJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 3,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS71m7TsAjtysrchyb4WsY0vJrO53MZ7QNBSw&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://assets.architecturaldigest.in/photos/63dcd0d043759bc4edc842c1/master/pass/11%20minimalist%20bedroom%20design%20tricks%20to%20create%20a%20calming%20space.jpg",
        kitchenImageUrl: "https://media.designcafe.com/wp-content/uploads/2021/05/13095507/modern-kitchen-design-ideas-for-your-home.jpg",
        livingAreaImageUrl: "https://www.bhg.com/thmb/dgy0b4w_W0oUJUxc7M4w3H4AyDo=/1866x0/filters:no_upscale():strip_icc()/living-room-gallery-shelves-l-shaped-couch-ELeyNpyyqpZ8hosOG3EG1X-b5a39646574544e8a75f2961332cd89a.jpg",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 4,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqZggIOeqpIdJAPNOepaAxacxdYYUq-CbcLg&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://media.designcafe.com/wp-content/uploads/2023/06/01112443/designer-bedroom.jpg",
        kitchenImageUrl: "https://hips.hearstapps.com/hmg-prod/images/modern-kitchen-ideas-colorful-light-fixtures-1577119061.jpg",
        livingAreaImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRCqi-eCEpz8GABQ17xRaGxCcF55ZJHytweA&usqp=CAU",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 5,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPgJbVSLGz2qkhJfGYtpfmrH3aM2yXsTw5Uw&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?auto=format&fit=crop&q=80&w=1000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVkcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
        kitchenImageUrl: "https://media.istockphoto.com/id/1456242777/photo/modern-japandi-mock-up-room-interior-design-and-decoration-with-green-pastel-counter-and.jpg?s=612x612&w=0&k=20&c=xWIYFrx09O-FGo1pizfoEz0A1E6Lsz_pIffTTnypI6U=",
        livingAreaImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjcQjqM9Cv6QXu3jLSFQJoxY0y2Ed8Ix1lhw&usqp=CAU",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 6,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLpudXfO07CTr418_ZD7e-zoRjtVi2no0UIQ&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://www.thespruce.com/thmb/AA70By8xZ6otga2XHLJ0gJpqNB0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/stunning-master-bedroom-design-ideas-4125545-hero-5782adcdc758407b884d92da7dbcbcbd.jpg",
        kitchenImageUrl: "https://img.staticmb.com/mbcontent/images/uploads/2023/1/kitchen-design-ideas.jpg",
        livingAreaImageUrl: "https://housing.com/news/wp-content/uploads/2023/03/Simple-living-room-ideas-for-your-home-f.jpg",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 7,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStibcJKbvkSkdTRQN8WZ1lyu2tffq7R3kaEQ&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://hips.hearstapps.com/hmg-prod/images/studio-heimat-coleridge-credit-frank-frances-11-644180b029ccc.jpg",
        kitchenImageUrl: "https://media.designcafe.com/wp-content/uploads/2020/05/09150825/blue-and-white-modular-kitchen-design.jpg",
        livingAreaImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUDRwmaw4hq7SqPMJkdbX09NZSaL_eLszGkw&usqp=CAU",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 8,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp5WA18LYwgjNoQ3MJHPtfQr-7Mo9hVQcjlg&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://images.woodenstreet.de/image/data%2FLooks%2F3.jpg",
        kitchenImageUrl: "https://st.hzcdn.com/simgs/d1a16682026968b5_14-3151/home-design.jpg",
        livingAreaImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaHfIGAJ_4cI1Vvq5J9jsA77va4aT1nGfTAg&usqp=CAU",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 9,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo-YtTn5DC78Y2cVaQiGb4Y5N7sv6rLujt1Q&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://media.designcafe.com/wp-content/uploads/2021/04/28110847/middle-class-indian-bedroom-design.jpg",
        kitchenImageUrl: "https://www.oppeinhome.com/upload/images/ueditor/20220818/10-Best-Luxury-Kitchen-Designs-1.jpg",
        livingAreaImageUrl: "https://cdn.habitusliving.com/wp-content/uploads/1.smallroomfeat.jpg",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
    {
        id: 10,
        house: "2BHK",
        rent: "15000",
        ownerName: "Komaraju Bablu",
        contactNumber: 6380681455,
        houseImageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF1wCylzK-940f88DpdDLqs1udmAMwsce86_Agxhk_YLraUwRHh9EJ_8xqUetCQDq3H24&usqp=CAU",
        location: "Hyderabad",
        bedRoomImageUrl: "https://www.nobroker.in/blog/wp-content/uploads/2022/07/Modern-Bedroom-Design.jpg",
        kitchenImageUrl: "https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/home-improvement/wp-content/uploads/2022/07/featured-image-kitchen-layouts.jpg",
        livingAreaImageUrl: "https://static.asianpaints.com/content/dam/asianpaintsbeautifulhomes/202209/traditional-living-room-ideas/title-traditional-living-room-design.jpg",
        area: "Super Built up area 1400 sq.ft.",
        furnishing: "Furnished",
        availableFrom: "immediate",
        address: "Hyder Nagar, Hyderabad",
        postedOn: "Owner on Nov 05, 2023",
        confirguation: "3 Bedrooms, 3 Bathrooms,3 Balaconies"
    },
]